### PR TITLE
Correction to stackable-opa-operator-server package name

### PR DESCRIPTION
**Pull request by pipern**
According to https://repo.stackable.tech/#browse/browse:deb-dev:packages and https://repo.stackable.tech/#browse/browse:rpm-dev:el8 the package is named with `-server`

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)

### CODE REVIEW

**Comment by pipern** [comment]
The other operators have the same thing FWIW - https://github.com/stackabletech/kafka-operator/blob/main/docs/modules/ROOT/pages/installation.adoc etc., so maybe the packages are named wrongly?

I currently have this installed:

```
ii  stackable-kafka-operator-server        0.1.0-nightly                         amd64        Stackable Operator for Apache Kafka
ii  stackable-opa-operator-server          0.1.0-nightly                         amd64        Stackable Operator for OpenPolicyAgent
ii  stackable-spark-operator-server        0.1.0-nightly                         amd64        Stackable Operator for Apache Spark
ii  stackable-zookeeper-operator-server    0.1.0-nightly                         amd64        Stackable Operator for Apache ZooKeeper
```

**Comment by pipern** [comment]
The name with `-server` is what was in the old "combined" documentation - https://github.com/stackabletech/documentation/commit/b316f65ab098f3d3bd79c251b071dca3ab58a30f#diff-48920fd40a21468cbed9ab168fd260a0f0a0e182946cb909886cb26c13b2f85cR195

**Comment by soenkeliebau** [comment]
You are absolutely right, that was an issue in our packaging. I hopefully fixed this yesterday as part of a larger structural overhaul of our operator repositories.

The PR on this repo was #72

**Comment by pipern** [comment]
OK so I understand the operating-system level package name will be `stackable-opa-operator` going forward (not `stackable-opa-operator-server`) so I'll close the PR without merge

**Pull request closed without merging**
