### PR TITLE
[Merged by Bors] - Document why we run as a DaemonSet

### PR DESCRIPTION
**Pull request by teozkr**
## Description

*Please add a description here. This will become the commit message of the merge request later.*

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by razvan** [comment]
Would you mind also writing a sentence down in the user facing docs ?

**Comment by teozkr** [comment]
The question is where it belongs in that case.. It doesn't really feel like something that deserves being front and center on the index page, but it's not really relevant for the task-oriented pages either..

**Comment by razvan** [comment]
For the hdfs operator I created an extra page with some implementation details but a paragraph on the "usage" page would be fine by me also.

**Comment by teozkr** [comment]
Okay, created an impl details page now then.

**Review by razvan — APPROVED** [review]
Nice!

**Pull request closed without merging**
