### PR TITLE
feat: Allow using custom images in tests

### PR DESCRIPTION
**Pull request by lfrancke**
# Description

Allow using custom images in tests

### CODE REVIEW

**Review by sbernauer — APPROVED** [review]
Thanks!

**Comment by sbernauer** [comment]
Please run `cargo update` to fix the yanked crate warning

**Comment by lfrancke** [comment]
I'll take a look at the cargo deny failure later

**Comment by lfrancke** [comment]
Done, let's see if it's better now

**Comment by lfrancke** [comment]
deny seems happy now

**Review by sbernauer — APPROVED** [review]
Thanks!

**Pull request merged**
