### PR TITLE
fix(kuttl tests): Use bundled userinfo rego utility

### PR DESCRIPTION
**Pull request by NickLarsenNZ**
Fixes the [test failures] (see [slack thread]):

_The effective fixes were cd3c31ed8bfff588fe2cc68c23a258a080f5ce65 and 7c308cc6f0959ffe353bab57ebd4a590cbf20866_

```
Traceback (most recent call last):
  File "/tmp/test-regorule.py", line 60, in <module>
    raise e
  File "/tmp/test-regorule.py", line 50, in <module>
something went wrong. last response: {'result': {}}
    assertions(username, response, 
```

- Use the bundled userinfo rego utility (partially reverts #580)
- Improve the output of the test scripts
  - print out the exception, it will have more information (from the `assertions()` function).
  - ruff formatting

[test failures]: https://testing.stackable.tech/job/opa-operator-it-weekly/13/console
[slack thread]: https://stackable-workspace.slack.com/archives/C02M1RE8S0Z/p1723187622613479

### CODE REVIEW

**Comment by NickLarsenNZ** [comment]
Kuttl tests now pass:

```
--- PASS: kuttl (32.09s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/keycloak-user-info_opa-latest-0.66.0_keycloak-23.0.1_openshift-false (68.65s)
        --- PASS: kuttl/harness/aas-user-info_opa-latest-0.66.0_openshift-false (32.08s)
PASS
```

**Review by sbernauer — APPROVED** [review]
Thanks for fixing this!
LGTM as tests passed

**Comment by sbernauer** [comment]
CC @nightkr, as you wrote the original test

**Comment by nightkr** [comment]
Yep, looks reasonable to me. Mea culpa.

**Pull request merged**
